DROP VIEW IF EXISTS "AuditChainHead";
ALTER TABLE "Attorney" ALTER COLUMN "updatedAt" DROP DEFAULT;
ALTER TABLE "Case" ALTER COLUMN "updatedAt" DROP DEFAULT;
ALTER TABLE "FeeAgreement" ALTER COLUMN "updatedAt" DROP DEFAULT;
ALTER TABLE "Tenant" ALTER COLUMN "updatedAt" DROP DEFAULT;
ALTER TABLE "User" ALTER COLUMN "updatedAt" DROP DEFAULT;
