ALTER TYPE "CaseStatus" ADD VALUE IF NOT EXISTS 'SUBMITTED_BY_CLIENT';
ALTER TYPE "CaseStatus" ADD VALUE IF NOT EXISTS 'SUBMITTED_BY_PARTNER';
ALTER TYPE "CaseStatus" ADD VALUE IF NOT EXISTS 'AWAITING_RESPONSE';
